workflows:
  ios-release:
    name: iOS Release

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.flairm.crm

    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios && pod install

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration